

package hexsoftwares_hospitalmanagementsystem;

import java.sql.Connection;
import javax.swing.JOptionPane;


/**
 *
 * @author Tshabalala MG
 */
public class HomePage extends javax.swing.JFrame {

   private final Connection connection;

    /**
     * Creates new form HomePage
     */
    public HomePage(Connection connection) {
        initComponents();

        this.connection = connection;
    }

    private HomePage(String exit) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbAddHead = new javax.swing.JLabel();
        btnAddHome = new javax.swing.JButton();
        btnViewPatients = new javax.swing.JButton();
        btnViewDrs = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();
        btnExitHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Management System");

        jPanel1.setBackground(new java.awt.Color(56, 142, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 350));

        lbAddHead.setBackground(new java.awt.Color(255, 255, 255));
        lbAddHead.setFont(new java.awt.Font("Clarendon Blk BT", 1, 18)); // NOI18N
        lbAddHead.setForeground(new java.awt.Color(255, 255, 255));
        lbAddHead.setText("Hospital Management System");

        btnAddHome.setBackground(new java.awt.Color(139, 195, 74));
        btnAddHome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAddHome.setForeground(new java.awt.Color(255, 255, 255));
        btnAddHome.setText("Add Patient");
        btnAddHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHomeActionPerformed(evt);
            }
        });

        btnViewPatients.setBackground(new java.awt.Color(139, 195, 74));
        btnViewPatients.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnViewPatients.setForeground(new java.awt.Color(255, 255, 255));
        btnViewPatients.setText("View Patients");
        btnViewPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientsActionPerformed(evt);
            }
        });

        btnViewDrs.setBackground(new java.awt.Color(139, 195, 74));
        btnViewDrs.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnViewDrs.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDrs.setText("View Doctors");
        btnViewDrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDrsActionPerformed(evt);
            }
        });

        btnBook.setBackground(new java.awt.Color(139, 195, 74));
        btnBook.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBook.setForeground(new java.awt.Color(255, 255, 255));
        btnBook.setText("Book Appointment");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        btnExitHome.setBackground(new java.awt.Color(139, 195, 74));
        btnExitHome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExitHome.setForeground(new java.awt.Color(255, 255, 255));
        btnExitHome.setText("Exit");
        btnExitHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(lbAddHead)
                .addGap(101, 101, 101))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewPatients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddHome, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnExitHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBook, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewDrs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbAddHead)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddHome, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewDrs, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnExitHome, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHomeActionPerformed

                  Patient PatientPageFrame = new Patient(connection);
                  PatientPageFrame.setVisible(true);
                PatientPageFrame.pack();
                PatientPageFrame.setLocationRelativeTo(null);//center
        
        
    }//GEN-LAST:event_btnAddHomeActionPerformed

    private void btnViewPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientsActionPerformed
               
                ViewPatients ViewPatientsPageFrame = new ViewPatients(connection);
                  ViewPatientsPageFrame.setVisible(true);
                ViewPatientsPageFrame.pack();
               ViewPatientsPageFrame.setLocationRelativeTo(null);//center
    }//GEN-LAST:event_btnViewPatientsActionPerformed

    private void btnViewDrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDrsActionPerformed
         ViewDoctors  ViewDoctorsPageFrame = new ViewDoctors(connection);
                  ViewDoctorsPageFrame.setVisible(true);
               ViewDoctorsPageFrame.pack();
               ViewDoctorsPageFrame.setLocationRelativeTo(null);//center
        
        
        
    }//GEN-LAST:event_btnViewDrsActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnExitHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitHomeActionPerformed
        
        HomePage frame = new HomePage("EXIT");
        
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","EXIT",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            
            System.exit(0);
            
            
        }
        
        
        
                
        
        
    }//GEN-LAST:event_btnExitHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
new HomePage("EXIT").setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddHome;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnExitHome;
    private javax.swing.JButton btnViewDrs;
    private javax.swing.JButton btnViewPatients;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAddHead;
    // End of variables declaration//GEN-END:variables
}

